apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: felix-application
  namespace: argocd
  labels:
    argocd.argoproj.io/refresh: hard
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-test
  sources:
    - ref: values
      repoURL: https://github.com/praneethkaturi/openshift-gitops-values.git
      targetRevision: HEAD
      
    - path: nginx/
      repoURL: <istio-helm-chart>
      targetRevision: HEAD
      helm:
        valueFiles:
        - $values/cae-config/cae-felix/env.yaml
        - $values/cae-config/cae-felix/dev/default.yaml
        - $values/cae-config/cae-felix/dev/dev-alln-01.yaml

    - chart: monitoring
      repoURL: repo-art.cisco.com/
      targetRevision: 1.0.4
      helm:
        valueFiles:
        - $values/cae-config/cae-felix/env.yaml
        - $values/cae-config/cae-felix/dev/default.yaml
        - $values/cae-config/cae-felix/dev/dev-alln-01.yaml
